name: Backend workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: List backend files
        run: |
          cd backend
          ls -la
      - name: Zip the Backend folder
        run: |
          cd backend
          zip -r ../backend.zip .
      - name: Upload ZIP to S3
        run: aws s3 cp backend.zip s3://${{ secrets.S3_BUCKET_NAME }}/backend.zip --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Green Environment (EC2)
        run: |
          aws deploy create-deployment \
            --application-name MovieApp \
            --deployment-group-name greenMovieBackend \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=backend.zip,bundleType=zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Health Check on Green Environment
        run: |
          curl -f http://${{ secrets.GREEN_EC2_IP }}/health || exit 1
      - name: Terminate Blue Environment
        run: |
          aws ec2 terminate-instances --instance-ids ${{ secrets.BLUE_EC2_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: Post-deployment verification
        run: echo "Deployment and Blue-Green strategy executed successfully."
